---
- name: Configure Elk VM with Docker\par
  hosts: elk\par
  remote_user: Miguel\par
  become: true\par
  tasks:\par
\cf1     # Use apt module\par
\cf0     - name: Install docker.io\par
      apt:\par
        update_cache: yes\par
        force_apt_get: yes\par
        name: docker.io\par
        state: present\par
\par
\cf1       # Use apt module\par
\cf0     - name: Install python3-pip\par
      apt:\par
        force_apt_get: yes\par
        name: python3-pip\par
        state: present\par
\par
\cf1       # Use pip module (It will default to pip3)\par
\cf0     - name: Install Docker module\par
      pip:\par
        name: docker\par
        state: present\par
\par
\cf1       # Use command module\par
\cf0     - name: Increase virtual memory\par
      command: sysctl -w vm.max_map_count=262144\par
\par
\cf1       # Use sysctl module\par
\cf0     - name: Use more memory\par
      sysctl:\par
        name: vm.max_map_count\par
        value: '262144'\par
        state: present\par
        reload: yes\par
\par
\cf1       # Use docker_container module\par
\cf0     - name: download and launch a docker elk container\par
      docker_container:\par
        name: elk\par
        image: sebp/elk:761\par
        state: started\par
        restart_policy: always\par
\cf1         # Please list the ports that ELK runs on\par
\cf0         published_ports:\par
          -  5601:5601\par
          -  9200:9200\par
          -  5044:5044\par
\par
\cf1       # Use systemd module\par
\cf0     - name: Enable service docker on boot\par
      systemd:\par
        name: docker\par
        enabled: yes\par
\f0\fs22\par
}
